# _config.yml
title: Enciclopedia Universitaria
description: La enciclopedia colaborativa universitaria más avanzada de habla hispana
baseurl: ""
url: "https://enciclopedia.arkflame.com"

# Configuración del backend
backend_url: "https://enciclopedia.arkflame.com/api"

# Build
markdown: kramdown
highlighter: rouge
# Cambiado: asegurar que las páginas salgan con su .html final
permalink: "/:path/:basename:output_ext"

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - .env

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO
twitter:
  username: enciclopediauniv
author: Enciclopedia Universitaria
lang: es

# Navegación
navigation:
  - title: Inicio
    url: /index.html
  - title: Categorías
    url: /categorias.html
  - title: Sobre nosotros
    url: /acerca.html
  - title: Ayuda
    url: /ayuda.html
